version: '3'
services:
  composer:
    image: 'composer:2.3'
    volumes:
      - ./:/app
    user: ${UID}:${GID}
    environment:
      HOME: /tmp
  node:
    user: ${UID}:${GID}
    image: 'node:14.17-buster'
    volumes:
      - ./:/app
    working_dir: '/app'
